---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"
vars:
  region: "%{hiera('region')}"

  private_network_cidr: "%{hiera('private_network_cidr')}"
  ingress_self: "%{hiera('ingress_self')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  database_instance_class: "%{hiera('database_instance_class')}"

  database_name: "%{hiera('database_name')}"
  database_master_user: "%{hiera('database_master_user')}"
  database_master_user_password: "%{hiera('database_master_user_password')}"

  snapshot_identifier: "%{hiera('snapshot_identifier')}"

  backup_retention_period: "%{hiera('backup_retention_period')}"
  backup_window: "%{hiera('backup_window')}"

  maintenance_window: "%{hiera('maintenance_window')}"
